### PR TITLE
Fixed some static properties which were declared with an equal sign.

### PR DESCRIPTION
**Pull request by brekk**

### CODE REVIEW

**Comment by taion** [comment]
This is not the syntax for class properties: https://github.com/jeffmo/es-class-fields-and-static-properties

**Comment by brekk** [comment]
I'm happy to leave this closed, but when trying to use the examples in the repo, webpack complains about those lines specifically. Using node `v.4.2.2`

**Comment by taion** [comment]
Make sure you're using the correct version of Babel with the correct settings.

Unless the proposal for class properties has just changed and the proposal above is out-of-date, what you have is not legal syntax.

**Comment by timdorr** [comment]
Fixed in 471e058e

**Comment by taion** [comment]
Oh, I see. Darn. I wonder if we can un-blacklist class properties in the examples? I like supporting IE8 in the core code, but it'd be nice if we didn't have to skip class properties everywhere.

**Comment by timdorr** [comment]
Well, blacklists go away in Babel 6, so we would just not enable it in the core and enable them in the example code. For now, this is fine.

**Comment by taion** [comment]
Well, it'd be a different preset. Anyway, nice catch.

**Pull request closed without merging**
