### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by Jocs**
update React-router to 2.0.0, should use `this.context.router.push()`

### CODE REVIEW

**Comment by timdorr** [comment]
Actually, this will work just fine. `Route` `component`s will get `router` on `props`. You can use either one. Context is always available down the tree.

**Comment by taion** [comment]
@timdorr Didn't we get rid of that? https://github.com/rackt/react-router/blob/da433a998f688884251d4fac811d5c577e80f5c9/modules/RouterContext.js#L73-L80

**Comment by timdorr** [comment]
Oh shit, I'm thinking of `route`. My bad.

**Comment by taion** [comment]
We should fix the rest, though. There are a few more calls into `this.props.router` in the examples.

**Pull request merged**
