### PR TITLE
UMD Wrapper

### PR DESCRIPTION
**Pull request by kirill-konshin**
Fix for https://github.com/rackt/react-router/issues/787

### CODE REVIEW

**Comment by kirill-konshin** [comment]
There was also a small mistake in `package.json`: it pointed to wrong `index.js`.

**Comment by gaearon** [comment]
Can you please squash into a single commit?

**Comment by kirill-konshin** [comment]
What is wrong with two commits? I can do that, but please provide justification, since it would be some amount of manual copy-paste...

**Comment by irvinebroque** [comment]
@kirill-konshin - lookup `git rebase -i` to squash your commits without having to do any copying or pasting: 

https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by kirill-konshin** [comment]
Created new PR https://github.com/rackt/react-router/pull/807

**Pull request closed without merging**
