### PR TITLE
Unwind recursion in loopAsync when possible

### PR DESCRIPTION
**Pull request by taion**
For #2922

### CODE REVIEW

**Comment by taion** [comment]
cc @mhart

**Comment by mhart** [comment]
This is a huge win for me – cut the stacks in our profiling down by at least 25% – and we only have 20 routes, so those with more routes will see even more benefits.

Thanks!

**Comment by taion** [comment]
Great, thanks. I'll let this sit a little more in case there are any more comments – we can't cut the next React Router RC without a new history RC anyway.

**Comment by timdorr** [comment]
Not sure why coveralls isn't coming back OK, but this looks good to me.

**Comment by gcorne** [comment]
@timdorr would you be up for back porting this to 1.0.x? I bumped into an `InternalError: too much recursion` on FF for Windows and this change fixes the issue for me.

**Comment by timdorr** [comment]
I'm not sure of our policy on patches for 1.0, but a PR would certainly make it more likely to happen :smile:

**Comment by taion** [comment]
I don't think we should – 2.x is essentially backward compatible.

**Comment by timdorr** [comment]
@gcorne I'm not sure of your particular use case, but @taion is right and upgrading should be painless. Just bump the version and start hunting for deprecation warnings. You can automate that with codemods too: https://github.com/reactjs/rackt-codemod

**Comment by gcorne** [comment]
> @gcorne I'm not sure of your particular use case, but @taion is right and upgrading should be painless.

Okay, I'll try that. Upgrading to 1.0.x was kind of painful, so I didn't expect the upgrade to 2.0.x to be painless. I'll give it a spin and see how it goes.

**Pull request merged**
