### PR TITLE
Update <Link> to just call push

### PR DESCRIPTION
**Pull request by taion**
Re-made from https://github.com/rackt/react-router/pull/2658.

Tests will fail until https://github.com/rackt/history/pull/173 is merged and released.
Codemod: https://github.com/rackt/rackt-codemod/pull/5.

I'm still using `context.history` here - we could potentially merge this and release it before the API changes to get rid of the deprecation warnings for users, per https://github.com/rackt/history/issues/172#issuecomment-162336396.

I'm going to be extremely busy over the next week and a half or so, and someone else might have to shepherd this to release (docs, changelog, &c.), which is why this branch is on the main repo instead of my personal fork.

### CODE REVIEW

**Comment by taion** [comment]
Re-made from https://github.com/rackt/react-router/pull/2658.

Tests will fail until https://github.com/rackt/history/pull/173 is merged and released.
Codemod: https://github.com/rackt/rackt-codemod/pull/5.

I'm still using `context.history` here - we could potentially merge this and release it before the API changes to get rid of the deprecation warnings for users, per https://github.com/rackt/history/issues/172#issuecomment-162336396.

I'm going to be extremely busy over the next week and a half or so, and someone else might have to shepherd this to release (docs, changelog, &c.), which is why this branch is on the main repo instead of my personal fork.

**Comment by taion** [comment]
This probably needs an update to https://github.com/rackt/react-router/blob/master/modules/PropTypes.js#L10 to include `push` and `replace` as well.

**Comment by timdorr** [comment]
I've got the same thing in a local branch, but it's for everything, not just `Link`. I also update to use `this.context.router`. 

However, at the moment, the tests are littered with deprecation warnings from React checking contextTypes and how we've implemented the deprecation via a getter. I'm holding off for the `useRoutes` refactor until I land some of this, because it will be broken code until that's available.

**Comment by timdorr** [comment]
@taion If you have any objections to my changes, let me know. Otherwise, it's :+1: from my end.

**Comment by taion** [comment]
:shipit:

Do whatever you want w/r/t squashing or whatever. And let's merge https://github.com/rackt/rackt-codemod/pull/5 afterward.

**Comment by timdorr** [comment]
Cool. Let me extract that function for creating the LD from `to` and then we should be good to go (and get the build green again! :smile:)

**Comment by timdorr** [comment]
headcrushing-kidsinhall1

Squashed. Merging now!

**Pull request merged**
