### PR TITLE
Tell users what's going on in postinstall

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
Avoids stuff like https://github.com/rackt/react-router/issues/2879.

**Comment by taion** [comment]
This looks like

```
-------------------------------------------------------------------------------
Built output not found. It looks like you might be attempting to install React
Router from GitHub. React Router sources need to be transpiled before use. We
will now make a best-efforts attempt to transpile the code. This will only work
if your development environment is set up appropriately.
-------------------------------------------------------------------------------
```

On failure:

```
-------------------------------------------------------------------------------
Failed to build React Router automatically. Please install React Router from
npm, or clone the repo locally and build the library manually.
-------------------------------------------------------------------------------
```

**Comment by bcherny** [comment]
:+1:

**Comment by taion** [comment]
Ah shoot, this is no good – apparently npm fixed it so that installs from Git no longer pull in things that are npm ignored.

**Comment by taion** [comment]
Ah, I just messed it up. We need to add back sources to the bundle.

**Comment by taion** [comment]
@mjackson I notice you commented as well on https://github.com/npm/npm/issues/7435. Does this look right to you?

**Pull request merged**
