### PR TITLE
[added] Added decorator conversion for mixins, included Navigation example

### PR DESCRIPTION
**Pull request by grgur**
Mixin support for ES6 classes through ES7 decorators

Usage:
```
import { NavigationDecorator } from 'react-router';

@NavigationDecorator
export default class Nav extends Component {
	// ...	
}
```

Internally I created `DecoratorUtils` with all the necessary logic. Converting a mixin to a decorator is a one-liner
```
export const NavigationDecorator = createDecorator(Navigation); 
```

### CODE REVIEW

**Comment by vramana** [comment]
@grgur Can you add an example in the demos with es6 name which people can refer to? Finding this PR for the example might be hard.

**Comment by grgur** [comment]
@vramana I think I have an example just for that.. working on it..

**Comment by grgur** [comment]
Added "meetup browser" demo. It's an ES.next (ES.later) demo app that uses React Router decorators (see `examples/meetup/app/views/GeoButton.js`) and Redux. 

/cc @vramana

**Comment by timdorr** [comment]
Can you rebase this against the latest master? There are a lot of commits mixed into this PR that are unrelated and make it really hard to read through and see what you did.

**Comment by grgur** [comment]
@timdorr Looks like something got messed up here so I cleaned up and created a [new PR](https://github.com/rackt/react-router/pull/1848). Sorry about that

@mjackson Sorry for the mess dude, if you wanna reapply label to the [other PR](https://github.com/rackt/react-router/pull/1848), that one might be more readable. Same content though

https://github.com/rackt/react-router/pull/1848

**Comment by vramana** [comment]
@grgur I think you can use this http://www.alexkras.com/19-git-tips-for-everyday-use/

**Comment by grgur** [comment]
@vramana lol, serves me right

**Comment by ryanflorence** [comment]
https://github.com/rackt/react-router/pull/1848#issuecomment-139313409

**Pull request closed without merging**
