### PR TITLE
[WIP] Warn if routes are unreachable

### PR DESCRIPTION
**Pull request by jackfranklin**
This is a first pass at #1923, with thanks to @knowbody and @grabbou for their help so far.

### CODE REVIEW

**Comment by taion** [comment]
Ouch - there's no better way than to manually check all ways routes might be bad?

**Comment by knowbody** [comment]
@taion I was thinking about the same thing. not sure if we want to loop through all of the routes just to display the warning message

**Comment by jackfranklin** [comment]
Yeah, I was going to ask that too. I'm not sure if there's a better way or not - obviously very new to this code base !

**Comment by knowbody** [comment]
maybe we could do something like a `DEBUG` mode and do variety of checks/validation for people, something for development only?

**Comment by taion** [comment]
The approach I would take would be to iterate through all leaf routes, generate the path, route to the path, then verify that we have the expected rendered routes.

Not sure we'd want to check this at run time though. Probably only in debug mode.

**Comment by knowbody** [comment]
@taion :+1:

**Comment by ryanflorence** [comment]
Hmm, since we support lazy route config I'm not sure how useful this is as a part of the library, maybe this is better as a tool outside of the project that you throw at your route config?

**Comment by taion** [comment]
That's definitely an option. Alternatively, we could offer some sort of helper utility for automated testing that does what I suggested above, that users can incorporate into their own test suites.

**Comment by timdorr** [comment]
I like that idea better. It's a development-only issue, so it should be provided as a development-only feature. Another option is to hide it behind a NODE_ENV flag, but that seems more prescriptive and opinionated.

**Comment by taion** [comment]
I'm going to close this PR for now, because I don't think this is the direction we want to take for validating route config. Let's move discussion back to #1923 as needed.

**Pull request closed without merging**
