### PR TITLE
[added] IndexRedirect

### LINKED ISSUE #1966: IndexRedirect component
The pattern from https://github.com/rackt/react-router/blob/v1.0.0-rc1/examples/redirect-using-index/app.js#L44 should be pulled out into a separate `IndexRedirect` component. It seems like a sufficiently common use case that it shouldn't just be a cookbook recipe from an example.

### PR DESCRIPTION
**Pull request by taion**
Closes #1966 

I removed the example because it would be no longer relevant/correct if this component is added.

### CODE REVIEW

**Comment by taion** [comment]
De-staled the PR (fixed merge conflict).

**Comment by mjackson** [comment]
Thanks, @taion! :D 

I rebased and committed in ca9e3b74a9be05b8b887a03b41c92d6ef1877298

**Comment by mjackson** [comment]
BTW, my apologies for taking so long to take a look at this. You're welcome to be a collaborator if you'd like a little more sway in getting things through :)

**Comment by taion** [comment]
I'd love to help if you think I can. Thanks for merging this.

**Pull request closed without merging**
