### PR TITLE
Add auth-with-shared-root example

### PR DESCRIPTION
**Pull request by jrouleau**
Demonstrates partial/lazy loading with auth and dynamic routes

See PR #1947

### CODE REVIEW

**Comment by taion** [comment]
Thanks for updating this! Looks like the Travis failures are from ESLint code style issues.

**Comment by jrouleau** [comment]
@taion Fixed

**Comment by knowbody** [comment]
@jrouleau as with all the examples now, could you also make the changes needed for React 0.14,
it's mainly the:

```js
import { render }  from 'react-dom'
```

thanks again for this example, I really like it

**Comment by knowbody** [comment]
@jrouleau thanks for the PR once again, it's merged. I just updated it tiny bit to use ReactDOM https://github.com/rackt/react-router/commit/d20a8ba9ac0dc329b023102a625d17ff76e89bc2

**Pull request merged**
