### PR TITLE
Try to use replaceState to verify history API.

### PR DESCRIPTION
**Pull request by stevemckenzie**
https://github.com/rackt/react-router/issues/535

### CODE REVIEW

**Comment by jiyinyiyong** [comment]
Does it mean we can use `history.replaceState {}, '', 'a-route'` to trigger react-router re-rendering?

**Comment by rpflorence** [comment]
I borrowed that code from modernizr, has it changed there?

**Comment by stevemckenzie** [comment]
https://github.com/Modernizr/Modernizr/pull/1463

**Comment by stevemckenzie** [comment]
@mjackson - I updated this a bit based on what we talked about at the conf. I didn't think this would become a priority again for a while but it now has for me.

For now I'm just using my fork though.

**Comment by ryanflorence** [comment]
Have you experiemented with an iframe as mentioned in https://github.com/Modernizr/Modernizr/pull/1463?

**Comment by ryanflorence** [comment]
@stevemckenzie ping ^

**Comment by ryanflorence** [comment]
closing due to inactivity, please holler if we should reopen this.

**Pull request closed without merging**
