### PR TITLE
Fixed some grammatical errors

### PR DESCRIPTION
**Pull request by achambers**

### CODE REVIEW

**Comment by gaearon** [comment]
Are you sure you're reading this correctly?

>Paths **that start** with `/` are absolute, paths **that don't** are relative,

You edits change the meaning.

**Comment by achambers** [comment]
Oh crap. I read it wrong and got confused and then changed it to something that was just as confusing ;) I still think the original can read better. I'll take a look at it when I get home. Sorry about that. Feel free to close the PR. Sorry to Easter your time there.

**Comment by gaearon** [comment]
NP :-)

I agree it could use rephrasing, let us know what you come up with!

**Comment by achambers** [comment]
Will do. And obviously I'm not sorry to Easter your time. That was an iPhone typo ;)

**Pull request closed without merging**
