### PR TITLE
Add auth-with-shared-root example

### PR DESCRIPTION
**Pull request by jrouleau**
Demonstrates partial/lazy loading with auth and dynamic routes

See #1941

### CODE REVIEW

**Comment by mjackson** [comment]
This looks like an interesting example! I'd love to get it merged. Can you please rebase?

**Comment by knowbody** [comment]
@jrouleau as Michael mentioned, could you make the updates and then we can merge it :smile:

**Comment by taion** [comment]
@jrouleau Will you have a chance to rebase this?

**Comment by jrouleau** [comment]
@mjackson 
I managed to bork the rebase. Had to recreate the PR. See #2309

**Pull request closed without merging**
