### PR TITLE
Allow async route getters return a reactElement

### PR DESCRIPTION
**Pull request by opichals**
Example

```
<Route getChildRoutes={function(cb) {
    cb(null, [<Route path="loaded"/>]);
}} />
```

### CODE REVIEW

**Comment by ryanflorence** [comment]
excellent :) if you can fix the conflicts I'll merge this.

**Comment by ryanflorence** [comment]
merged 27c5ba153e6bbac607160abdaeb3f011fd5d1c34

**Comment by ryanflorence** [comment]
ah crap, I screwed it up and got rid of you as an author, I'm sorry :(

**Comment by opichals** [comment]
No worries, the patch itself is more important :)

**Pull request closed without merging**
