### PR TITLE
Hash documentation update concerning scroll management.

### LINKED ISSUE #2605: Clarification of Link 'hash' key documentation
I'm been struggling and struggling with making hash links (anchor links) function properly with react-router.

Full example source here https://github.com/naemono/bootstrap-carousel-react

With a simple router config of this, history set to 'history/lib/createBrowserHistory'

```
render((
  <Router history={history}>
    <Route path="/" component={App}>
    </Route>
  </Router>
), document.getElementById('main'))
```

A div defined by this in src/views/Marketing.js:

```
<div id='marketing'>
```

And a link defined in navbar (src/views/NavBar.js) like so:

```
<li><Link to='/' hash='#marketing'>Marketing</Link></li>
```

It just doesn't work.  The featurette link right after it works fine as this:

```
<li><a href="#featurette">Featurette</a></li>
```

I don't know if I'm mis-reading the documentation, or it's just broken, but any clarification would greatly help.

I am aware that SO is the proper place for this type of question, and there have been a number of them, but they all mention changing the history from a hashhistory, which I've already done.

Thanks for any help you can provide, I'll be happy to give you a PR for the docs once I can understand the proper way to get this functional.

### PR DESCRIPTION
**Pull request by naemono**
Doc notes around scroll position management not being currently handled by react-router.

Closes #2605

### CODE REVIEW

**Comment by taion** [comment]
Can you write that as:

**Note**: React Router currently does not manage scroll position, and will not scroll to the element corresponding to the hash. Scroll position management utilities are available in the [scroll-behavior](https://github.com/rackt/scroll-behavior) library.

**Comment by naemono** [comment]
@taion Now I understand your comment in the issue about scroll-behavior.  Will do.

**Comment by taion** [comment]
Cool - can you squash the commits?

**Comment by naemono** [comment]
@taion Sure thing... done

**Comment by taion** [comment]
Thanks!

**Pull request merged**
