### PR TITLE
update react to v0.14.0

### PR DESCRIPTION
**Pull request by knowbody**

### CODE REVIEW

**Comment by knowbody** [comment]
@mjackson done

**Comment by mjackson** [comment]
Awesome. Thanks @knowbody!

I guess this means we should probably have a peer dep on React 0.14 too.

**Comment by knowbody** [comment]
@mjackson shall we merge that now when the RC3 is out? also as @ryanflorence mentioned yesterday, do we need 0.14 as a peer dependency?

**Comment by taion** [comment]
@knowbody I don't think it's necessary to set that peer dependency. v1.0.0-rc3 is still fully compatible with React v0.13.x, is it not?

**Comment by knowbody** [comment]
it is @taion

**Comment by taion** [comment]
I'd definitely suggest not immediately adding a peer dependency on React v0.14, then, since all that would so is potentially give people using 1.0.0 and React v0.13 peer dependency errors.

**Comment by mjackson** [comment]
The only reason I mentioned the peer dep is because this PR makes us incompatible with React 0.13. So that would give people a clue that they need to update their version in order to use it.

In any case, I'm going to open a separate issue where we can discuss a plan for 0.14 support.

**Comment by taion** [comment]
@mjackson: How so? This PR appears to update only the tests, unless I'm missing something.

**Comment by mjackson** [comment]
> This PR appears to update only the tests

Oh! You're right. Let's do this!

**Pull request merged**
