### PR TITLE
Add a license file

### PR DESCRIPTION
**Pull request by eknuth**
So I can link to it. Thanks!

### CODE REVIEW

**Comment by timdorr** [comment]
Do @mjackson and @ryanflorence want to be on the copyright line?

**Comment by knowbody** [comment]
@timdorr for the same reason I left it

**Comment by mjackson** [comment]
@eknuth Here's your link:

https://opensource.org/licenses/MIT

**Comment by eknuth** [comment]
Sorry for the confusion, but I need a license file in your repository that i can link to as a public attribution that the router is indeed using the MIT license. package.json and readme are one thing, but the license file is what I need.

We are using your awesome routing module in several projects at New Relic. I appreciate the work you have done. If there is anything I can do to make this happen, just let me know.

**Comment by mjackson** [comment]
Sorry for closing so quickly, @eknuth. Hopefully you've got what you need now :)

**Pull request merged**
