### PR TITLE
Set react to v0.14.0-alpha2

### PR DESCRIPTION
**Pull request by laskos**

### CODE REVIEW

**Comment by laskos** [comment]
Travis failed becouse of ``Firefox Disconnected`` but all tests pass on my local machine.
zrzut ekranu 2015-05-21 02 51 41

**Comment by ryanflorence** [comment]
package.json has been updated to reflect the alpha version, you can `npm install react-router@alpha` now

**Comment by laskos** [comment]
@ ryanflorence The point of this PR is use React 0.14. 1.0.0-alpha2 version still uses 0.13.x in peerDependencies which makes collision when I try to build app with React 0.14.x.

**Comment by johannestroeger** [comment]
just do add my 2 cents to this...

@laskos as npm@3 will be released soon, this peerDependency issue will no longer throw an ERR, just a WARN. IMO this feature caused more troubles and was never really a good solution. BTW as we learned already in the `web 1.0` - never patronize users...

@ryanflorence so why do you still eager to use peerDependency? see #1216 #98 #1190 and so on.

**Comment by ryanflorence** [comment]
@laskos I think I replied to the wrong thread here, sorry about that. If we changed the dep to v0.14.0-alpha2 then everybody using the router on stable react (0.13) would have install issues. We keep the peer dep pointing to the latest stable release as soon as we confirm that we support it.

@johannestroeger I don't think declaring that our library is known to work with a specific version of react is patronizing. Can't wait for npm 3 that doesn't auto-install peerDeps, and doesn't throw errors when they are out of sync. For now, though, do you know how we can declare the versions of react that we are compatible with?

**Comment by tizmagik** [comment]
@johannestroeger How to get around the peerDependency issue until npm@3 is released?

**Pull request closed without merging**
