### PR TITLE
Use location descriptor in onEnter redirect

### LINKED ISSUE #2828: replaceState callback in onEnter should take location descriptor

### PR DESCRIPTION
**Pull request by taion**
Fixes #2828

### CODE REVIEW

**Comment by taion** [comment]
@timdorr 

https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md#link-to-and-isactive-take-location-descriptors needs to be updated to include this, but I didn't want to break the tiny.cc link.

I guess we should probably add a codemod here.

**Comment by timdorr** [comment]
I can update the tiny.cc links if the URL structure changes. That's why I chose them over bit.ly :smile:

**Comment by taion** [comment]
@timdorr Do you want me to update that section, then, and you can update tiny.cc as you merge?

**Comment by timdorr** [comment]
Yeah, go for it. I'll take care of the links.

**Comment by taion** [comment]
@timdorr Updated the PR. Can you update the links and merge when ready?

**Comment by timdorr** [comment]
Sorry, I didn't have a chance to look over this last night as it's more substantial than just some docs updates. 

LGTM though.

**Comment by timdorr** [comment]
Link updated: http://tiny.cc/router-isActivedeprecated

**Pull request merged**
