### PR TITLE
Update Introduction.md

### PR DESCRIPTION
**Pull request by AshCoolman**
Readers may not be aware what/where IndexRoute is

### CODE REVIEW

**Comment by timdorr** [comment]
This just moves around the question of what `IndexRoute` is, since it doesn't really explain it. If anything, the note should be closer to the actual usage of `IndexRoute`.

But since this is just an overview/introduction, I don't think it's the right time to dive into more detail on the component API we provide.

**Comment by taion** [comment]
Maybe we can add the `IndexRoute` import at https://github.com/AshCoolman/react-router/blob/59d99ff05bfca0534c9c46c3557cb6ceb466f5a5/docs/Introduction.md#with-react-router?

**Comment by timdorr** [comment]
Nah, this isn't 100% real code anyways. Lots of stuff is skipped for the sake of brevity and to focus on concepts. It's the same reason we don't show the React imports.

**Comment by taion** [comment]
We do have the React imports in that listing above, though.

**Pull request closed without merging**
