### PR TITLE
Update ServerRendering.md

### PR DESCRIPTION
**Pull request by asaf**
Replaced deprecated static call to createLocation

### CODE REVIEW

**Comment by joneslee85** [comment]
@asaf :+1:

**Comment by timdorr** [comment]
There is no need for this. [`match` accepts `location` as a string](https://github.com/rackt/react-router/blob/master/modules/match.js#L38-L39). You don't have to dive into the history API to use react-router on the server.

**Comment by asaf** [comment]
@timdorr Even better, so docs should be updated accordingly!

**Comment by timdorr** [comment]
@asaf: I've got you covered! :smile: 508fa6ed

**Comment by mjackson** [comment]
Thanks, @timdorr :)

**Pull request closed without merging**
