### PR TITLE
[added] router.replaceRoutes(children)

### PR DESCRIPTION
**Pull request by gaearon**
Supersedes #606, that's the only missing piece. Let me know if you want tests for this; I'm not sure where to put them because there are not tests for `addRoutes` either. But this has been working for me for a few weeks so I don't think it's problematic.

### CODE REVIEW

**Comment by gaearon** [comment]
Don't know what's failing Travis but locally tests run fine.

**Comment by gaearon** [comment]
Note: I slightly tweaked this PR to include `isBootstrapping`.
This is necessary to force dispatch in case `replaceRoutes` affected current route.

**Comment by gaearon** [comment]
This still doesn't quite work as desired.

We talked with @mjackson about this and maybe it's worth extracting either some parts of `dispatch` or `run` into some kind of `refresh` method.

The scenario I need to support is following:

1. User goes to `/a`, `A` matches
2. I call `replaceRoutes` with new route config where `/a` maps to `B`
3. Router should be smart enough to figure out routes changed and `dispatch` a change

Right now, `dispatch` exits early with `prevPath === path`.

In this PR, I tried to fix this with `force` parameter, but it will only kick off dispatch if I call `stop()` and then `run()` after replacing routes. This is not correct either because we want to dispatch immediately after `replaceRoutes`.

**Comment by gaearon** [comment]
Changed the code to add `refresh()` method that works correctly regardless of whether the router is running or not. I removed `callback` argument from `dispatch` because it was always the same `dispatchHandler`. I already needed to move `dispatchHandler` outside `run` to implement `refresh`. Now that `dispatchHandler` was at the top, passing it as the last argument in each `dispatch` call seemed redundant. This also removes some of the perceived cognitive load IMO (`dispatch` always called the same callback but it wasn't apparent until you looked closely at the source).

**Comment by yaru22** [comment]
+1. This seems to be what I'm looking for. Can't wait to try it out.

**Comment by gaearon** [comment]
Rebased on top of current master. Can we please get this in?

**Comment by mjackson** [comment]
@gaearon This looks great. Thank you :)

**Comment by gaearon** [comment]
YEAAH

**Pull request merged**
