### PR TITLE
add example: autonav

### PR DESCRIPTION
**Pull request by iamdustan**
Used the existing example `auth-flow` as the base, so some of the views (`Dashboard`) are the exact same.

### CODE REVIEW

**Comment by ryanflorence** [comment]
ooh, that's pretty cool, mind updating to the 1.0 API? its on latest master now, docs/examples are up-to-date

**Comment by iamdustan** [comment]
It seems as though `getCurrentRoutes` is no more. How would I get the array of currently matched routes now?

**Comment by iamdustan** [comment]
Nvm. Got it working at least to the depth of this demo. Should be good to go.

**Comment by ryanflorence** [comment]
I have some ideas for this, closing and will revisit after 1.0.

**Comment by iamdustan** [comment]
:thumbsup: I dig. I suspect your ideas knowing the internals will be much better than mine. :)

**Pull request closed without merging**
