### PR TITLE
isActive for dynamic index routes

### LINKED ISSUE #2072: Link onlyActiveOnIndex breaking with dynamic routing
So I have some route config down low in my hierarchy like such:

```js
path: 'dashboard',
getComponents(location, callback) {
  require.ensure([], (require) => {
    callback(null, require('./components/dashboard/Dashboard'));
  })
},

getIndexRoute(location, callback) {
  require.ensure([], (require) => {
    callback(null, require('./components/dashboard/DashboardIndex'));
  })
},

getChildRoutes(location, callback) {
  require.ensure([], (require) => {
    callback(null, [
     {
       path: 'blah',
       component: require('./components/dashboard/blah')
     },
...
```

In my Dashboard component, i have this:
```js
// I saw IndexLink but i noticed that it wasn't probably exported in the latest rc?
<Link to="/dashboard" onlyActiveOnIndex={true} activeClassName="active">Index</Link>
```

So without dynamic routing, whenever I'm at `/dashboard', the Link is correctly detected as active, but once I stuck in dynamic routing it broke. My current solution is to just make the index route some named route, but it would be nicer to not have a /index. :) Any ideas?

### PR DESCRIPTION
**Pull request by taion**
Fixes #2072

### CODE REVIEW

**Comment by taion** [comment]
Can we make the coveralls check be a little more lenient?

A simpler implementation might be possible - make `getMatchingRoute` be e.g. `getMatchingRouteIndex` and just verify that all remaining routes have no `path` specified. For completeness we would then maintain the invariant in `getIndexRoute` in `matchRoutes` (or elsewhere) that index routes do not have `path` specified.

I don't want the merge conflict with #2421 though.

**Comment by taion** [comment]
Updated with a much simpler check that I believe covers all the relevant cases.

**Comment by knowbody** [comment]
thanks @taion! I like it!

**Comment by taion** [comment]
Ack I wanted to squash this first. Oh well.

**Pull request merged**
