### PR TITLE
(WIP) Record and restore scroll positions

### PR DESCRIPTION
**Pull request by gaearon**
**WORK IN PROGRESS, DO NOT MERGE**

This PR is a work-in-progress bringing scroll position save and restore to the 1.0 branch.

### CODE REVIEW

**Comment by gaearon** [comment]
@mjackson @ryanflorence 

I would like your attention here before I proceed with writing tests for this.

Michael suggested me to implement behaviors as components and I really liked this idea.

Here's how scrolling works here:

* Histories descending from `DOMHistory` should call `recordScrollPosition()` on their `push` actions (we might actually be able to also call it for `pop` action in `BrowserHistory` to preserve Forward button position; we removed Forward restoration in previous versions because it didn't behave consistently in `HashLocation`, but now we can support them separately).

* Custom histories may override `getScrollPosition()` (this would fix #1112).

* `createRouter` now accepts a second argument: `behavior`. Here's where it gets interesting. `behavior` must be a React class. By default it is `BrowserScrollBehavior` but you can also supply `react-router/ScrollToTopBehavior` (not exported by default so you don't drag it if you don't use it). People can also implement their own behaviors.

Now what's a behavior? It's a React class that `Router` wraps its children into. It receives router state as props (and can do custom stuff in response to it), and the router's matched children as regular children. It may decide to do some post processing on them, or it may just hook into `componentDidUpdate` to update scroll position.

Here's how built-in behaviors work:

### createScrollBehavior.js

```js
var React = require('react');
var PropTypes = require('./PropTypes');

function createScrollBehavior(applyScrollPosition) {
  class ScrollBehavior extends React.Component {
    static propTypes = {
      location: PropTypes.location,
      children: React.PropTypes.element.isRequired
    }

    componentDidUpdate(prevProps) {
      var prevLocation = prevProps.location;
      var location = this.props.location;

      if (prevLocation.path === location.path)
        return;

      applyScrollPosition(location.scrollPosition);
    }

    render() {
      return React.Children.only(this.props.children);
    }
  }

  return ScrollBehavior;
}

module.exports = createScrollBehavior;
```

### BrowserScrollBehavior

```js
var createScrollBehavior = require('./createScrollBehavior');

function restoreScrollPosition(scrollPosition) {
  if (scrollPosition) {
    window.scrollTo(scrollPosition.x, scrollPosition.y);
  } else {
    window.scrollTo(0, 0);
  }
}

module.exports = createScrollBehavior(restoreScrollPosition);
```

### ScrollToTopBehavior

```js
var createScrollBehavior = require('./createScrollBehavior');

function scrollToTop() {
  window.scrollTo(0, 0);
}

module.exports = createScrollBehavior(scrollToTop);
```

User can also create custom behaviors for scrolling (#1112) or maybe something else.

User may also compose behaviors freely as they're just React classes.

**Comment by ryanflorence** [comment]
first glance, this is awesome.

**Comment by gaearon** [comment]
This is currently missing `ignoreScrollBehavior` but that too, should be possible, by introspecting the route info passed by the `Router` to the behaviors.

**Comment by mjackson** [comment]
Interesting. I really like this approach a lot. I wonder if we could do `createHistory` like this as well...

**Comment by gaearon** [comment]
All right, I added `ignoreScrollBehavior` back. If the rest is fine, I can write tests tomorrow.

**Comment by gaearon** [comment]
By the way, we're going to need a separate `index.umd.js` that exports all histories and scroll behaviors for the UMD build.

**Comment by gaearon** [comment]
I wonder if @ryanflorence can also do the async props via a similar approach.

**Comment by mjackson** [comment]
If we do everything like this – as components that just take router props and pass them down the chain – we can have a "middleware" API that anyone can build stuff on.

**Comment by cpojer** [comment]
Personally I'd prefer `createRouter` to stay continue taking only a single argument. How about putting the behavior on the root route like `<Route behavior={Behavior} />`?

**Comment by gaearon** [comment]
Yes, I'm not super happy about it either.
In fact the guys had an epiphany about componentization that I'm sure they'll share soon.

**Comment by gaearon** [comment]
Superseded by c5966be71e54a83029c6f31f22102519202dc724 and 663a97e242a284c77f70e3f406f1e50a8fdb7dcd.

**Pull request closed without merging**
