### PR TITLE
Fix typo 'router' to 'history' in v2.0.0 upgrade guide

### PR DESCRIPTION
**Pull request by vishaltelangre**

### CODE REVIEW

**Comment by taion** [comment]
That part is demonstrating what the _old_ usage was.

**Comment by vishaltelangre** [comment]
@taion Yes, but the old signature is described as:
```
// v1.0.x
router.isActive(pathname, query, indexOnly)
```
which should be

```
// v1.0.x
history.isActive(pathname, query, indexOnly)
```

**Comment by taion** [comment]
Oops, I misread. Thanks!

**Comment by vishaltelangre** [comment]
:smile:

**Pull request merged**
