### PR TITLE
[added] node_modules to gitignore

### PR DESCRIPTION
**Pull request by contra**
this makes contributing easier imo

### CODE REVIEW

**Comment by gaearon** [comment]
#328 #640

I'm with you though..

**Comment by nickcolley** [comment]
Yeah my editor explodes as it tries to parse node_modules to lint it. :+1:

**Comment by contra** [comment]
I understand that you should have a global ignore set up but most people trying to contribute do not, and this is just an unnecessary frustration out of stubbornness in what should be a really simple process

**Comment by gaearon** [comment]
:+1:

**Pull request merged**
