### PR TITLE
Fix build configs

### PR DESCRIPTION
**Pull request by taion**
This is the rest of #2517, &c. Largely no-op but we should merge to clean/freshen these.

### CODE REVIEW

**Comment by mjackson** [comment]
Please match existing code style in .travis.yml as well.

**Comment by taion** [comment]
This is actually the code style used by Travis in their guides though: http://docs.travis-ci.com/user/languages/javascript-with-nodejs/.

I'm fine with changing it back, but I'd think it'd generally be better to be consistent with upstream styling there.

**Comment by mjackson** [comment]
Yes, please change it back and just add the lines we need for the cache.
Thanks!

**Comment by taion** [comment]
Updated both here and for the corresponding PR on history - unless you specifically want the Node version dialed back to `"4"` instead of `stable`.

**Comment by mjackson** [comment]
Thank you, @taion!

**Pull request merged**
