### PR TITLE
Fix missing semicolon in nginx configuration snippet

### PR DESCRIPTION
**Pull request by bcremer**

### CODE REVIEW

**Comment by taion** [comment]
Thanks!

**Comment by taion** [comment]
I'm really confused by why the Travis build is failing. It's clearly not the fault of this commit, though, so I'm going to merge it anyway, then assume fetal position and cry until the build gets better.

**Comment by knowbody** [comment]
@taion I've checked it. Some issues with browserify, probably will be fixed in a bit. But this commit can't brake anything anyway

**Comment by knowbody** [comment]
@taion master is :white_check_mark: again :smile:

**Pull request merged**
