### PR TITLE
Updated testing docs for 1.x

### PR DESCRIPTION
**Pull request by chiedojohn**
I put together some updated testing docs for React-router 1.x.

There wasn't much to write as testing should "just work" with react-router 1.x but mainly this doc helps those upgrading from prior testing setups.

As I do more testing and run into issues, I can add more to the docs.

Re issue #2149

### CODE REVIEW

**Comment by chiedojohn** [comment]
I placed the testing docs at the same location as the old testing docs so that the links already existing scattered through blogposts and forums will still work.

**Comment by knowbody** [comment]
Very cool, thanks for that, mind adding an example to this guide as well? 

@chiedojohn also maybe worth mentioning `babel-jest` and the config with webpack, what do you think?

**Comment by chiedojohn** [comment]
I think that's a good call! @knowbody 

I mentioned babel-jest. I don't use webpack though so maybe someone else could modify submit a PR for that portion?

In regards to the example. Do you think I should add that to the examples directory and link to it? Or just create the example in testing.md?

**Comment by knowbody** [comment]
Cool, I fill the gap with webpack.

The example just put it in the bottom, something like:

### Example:

```js
some code
```

and this is how you can test it:

```js
some code
```

**Comment by chiedojohn** [comment]
Example added @knowbody

**Comment by knowbody** [comment]
awesome, thank you!
one last thing can you squash the commits? and then I'll merge

**Comment by chiedojohn** [comment]
Squashed!

**Pull request merged**
