### PR TITLE
added transition state

### PR DESCRIPTION
**Pull request by ryanflorence**
pinterest example almost works now, just need to
add the omitted path searching to the route
matching.

this isn’t sending the state to transition hooks
but totally should

### CODE REVIEW

**Comment by ryanflorence** [comment]
I like `transitionState` the most.

- `request` has a lot of prior meaning we'd be swimming up stream to explain to people
- `transitionContext` has a little bit of prior meaning with `context` in React, and its not quite the same
- `transitionInfo` I like but ...
- `transitionState` completely mirrors the ignored `state` feature of `pushState`, just `state` would be a good name outside of React, but inside of React I like the `transition` prefix. I don't think it will take as much to understand as the other names.

**Comment by taurose** [comment]
`transitionState` makes most sense to me, too.

Another one:

* `payload`: as in request payload. Originally used in #828 (not sure why he changed it to `data`)

**Comment by mjackson** [comment]
What if we just kept it on `location.state` ? `key` would be part of this.

**Comment by taurose** [comment]
Just calling it `state` might be a bit confusing since this is different from `history.state` and `key` (used one time only instead of being persisted). I imagine we might want to add a persistent `state` (built on top of `key`) in the future.

**Comment by ryancole** [comment]
Does this relate to the issue regarding the static transition functions not being able to make use of non-singleton flux stores on props, etc?

**Pull request closed without merging**
