### PR TITLE
getDOMNode() has been deprecated. Use React.findDOMNode() instead.

### PR DESCRIPTION
**Pull request by vasanthk**
https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html
https://facebook.github.io/react/docs/component-api.html#getdomnode

### CODE REVIEW

**Comment by nvartolomei** [comment]
Afaik the deprecation has nothing to do with `refs`. getDOMNode is deprecated and removed from Component class only.

**Comment by ryanflorence** [comment]
thanks @vasanthk, mind updating this to latest master?

**Comment by vasanthk** [comment]
@ryanflorence Updated it to the latest master. Does it look fine now?

**Comment by krzysiek1507** [comment]
https://github.com/rackt/react-router/blob/0d053e301b3ddfecad4683f1b4d07897e90c56e8/examples/master-detail/app.js#L124-L125

**Comment by vasanthk** [comment]
@krzysiek1507 Modified it too. Thanks :)

**Comment by gaearon** [comment]
Can you squash into a single commit please?

**Comment by vasanthk** [comment]
@gaearon Getting an 'error: could not apply' when I try to squash the commits. Wonder if few of my commits have become useless after a merge. Could you help me out with the squash?

**Comment by gaearon** [comment]
@vasanthk 

I usually do this:

```
git fetch upstream
git checkout mybranch
git merge upstream/master

# if necessary, resolve conflicts and git commit
# ...

git reset --soft upstream/master
git commit -am 'Some cool description for a single commit'
git push -f
```

**Comment by vasanthk** [comment]
@gaearon That worked. Thanks :+1:

**Comment by gaearon** [comment]
:+1:

**Pull request merged**
