### PR TITLE
Avoid using getters as they can't be properly es5-shimmed for IE8

### LINKED ISSUE #1022: Getter in TestLocation breaks IE8 support
It seems that you've changed JS transpiler from jstransform to babel since 0.12.3. However Babel doesn't support class inheritance in IE8 (see babel/babel#703).

Any suggestions?

### PR DESCRIPTION
**Pull request by pkese**
In my case, this fixes #1022 and #1040

### CODE REVIEW

**Comment by frankdejonge** [comment]
I've applied this patch and it works for me :+1:

**Comment by bloodyowl** [comment]
:+1: just ran into this bug.

**Comment by BerkeleyTrue** [comment]
Should this be changed here https://github.com/rackt/react-router/blob/master/modules/locations/TestLocation.js#L16 instead of the compiled version?

**Comment by frankdejonge** [comment]
@BerkeleyTrue I'd say so.

**Comment by bloodyowl** [comment]
you can patch it like this then

```diff
 class TestLocation {
 
   constructor(history) {
     this.history = history || [];
     this.listeners = [];
     this._updateHistoryLength();
+    this.needsDOM = false;
   }
-
-  get needsDOM() {
-    return false;
-  }
```

**Comment by damassi** [comment]
Surprising how much hell that single getter has caused!  Would love for this to be merged in.

**Comment by scvnc** [comment]
:+1: I'm seeing the es5-shim explode in IE8.  Continued IE8 support would be......  great...

**Comment by damassi** [comment]
@ryanflorence or @mjackson - I know you guys have been traveling, but would love a comment on this since it is such high impact.  I'm currently running a fork of react-router just to keep our company's application alive, all due to a single, seemingly random keyword `get`.  

Do you plan on continuing support for ES3, or no?  If no, it would be nice to get an official statement on this so I can begin migrating our application over.  (Crossing fingers.)

**Comment by BerkeleyTrue** [comment]
This should be closed in favor of https://github.com/rackt/react-router/pull/1143

**Comment by rey-wright** [comment]
This pull request doesn't work for me. I get the following error (when I delete the get method and put ```value: false``` in it's place: ```Invariant Violation: ReactCompositeComponent.getChildContext(): childContextTypes must be defined in order to use getChildContext()```

**Comment by scvnc** [comment]
I am also receiving `Invariant Violation: ReactCompositeComponent.getChildContext(): childContextTypes must be defined in order to use getChildContext()` with IE8 + this PR + React 0.13.1  + my app.

**Comment by youuycom** [comment]
I am also receiving Invariant Violation: ReactCompositeComponent.getChildContext(): childContextTypes must be defined in order to use getChildContext() with IE8 + this PR + React 0.13.1 + my app!!!

**Comment by leoselig** [comment]
+1 on this
without IE8 support we need to drop react-router for our application stack

**Comment by damassi** [comment]
@leoselig - I was communicating with Ryan Florence on twitter yesterday about this PR and he said that they aim to ensure that React Router will always be able to run where React runs.  They've just been busy rewriting the thing.

**Comment by StefanBilliet** [comment]
That pull request does seem to work; I haven't had any problems anymore in IE8

**Comment by pkese** [comment]
This pull request (that I initially authored) was indeed wrong. The version that @bloodyowl suggested and is now also opened as pull request #1143 is the correct one, so please move further discussion there.

To anyone wishing to fix their IE8 build, just apply the patch from #1143 and then run `npm install`.

@scnvc `es5-shim` is rather obsolete... you'd better use `core-js` as shim. The shim version that comes with babel works wonders. Id suggest to use it as `babel-core/browser-polyfill` and load that before any other javascript.

**Pull request closed without merging**
