### PR TITLE
[added] Make router run work client side when given history class instance

### LINKED ISSUE #1486: 1.0.0-beta3: Router Run client side
First, I'm all about Universal JavaScript.

While I think the move to make Router a component is an awesome idea, it doesn't work that great when you are working server side with apps where some routes are react and some are not. It also breaks the symmetry that I like when building universal apps.

While server side Router Run works great and everything renders correctly, client side Router Component expects something different and fails.

It seems like it runs the exact same code that Router run goes when given a history object instead of a location object. 

I think there is a pretty simple solution:
```
if (history) {
  if (components and branch and params) {
    return setState({ components, branch, params })
  }
  // make componets from children
```
I'll be forming a PR soon if no one disagrees as I need this functionality to move forward. I'd like to open a discussion here and see if this is something RR team would like to support.

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
Check if Router run was given a history class instance.
Then setup history class instance.
Add history object to nextState on successful callback.

closes #1486

### CODE REVIEW

**Comment by faergeek** [comment]
+1

**Comment by olegakbarov** [comment]
That would be very helpful, indeed

**Comment by BerkeleyTrue** [comment]
There is some refactoring that could be done in ComponentWillMount to remove some of the repetition. Didn't want to make super drastic changes without some word on whether this is something that would be merged.

**Comment by BerkeleyTrue** [comment]
Purposely removed UMD files as they had many compilation difference unrelated to this commit.

**Comment by BerkeleyTrue** [comment]
There is one hiccup. Not sure how to add `this.routes` in to the equation. Will pick it up again tomorrow.

**Comment by BerkeleyTrue** [comment]
Alright, fixed. Easy-peasy lemon squeeze-y.

**Comment by aripalo** [comment]
Hmm so does this fix #1402 (that invalid checksum error with isomorphic react because of `<noscript>`) and #1486 ..? If so, would love see this one merged then as that checksum error really is a pain in the butt for isomoprhic apps.

**Comment by BerkeleyTrue** [comment]
No sure about #1402, if you are having that issue can you give this pr a whirl?

**Comment by ryanflorence** [comment]
the api on master allows for this, we'll have guides around usage soon, but here's the guide for server rendering, which hopefully is enough for right now for you to see how to use client side https://github.com/rackt/react-router/blob/670b5ea630668be5bfa4079586d3fdd9306ba75f/docs/ServerRendering.md

**Comment by BerkeleyTrue** [comment]
@ryanflorence The same can be run client side?

**Pull request closed without merging**
