### PR TITLE
HashLocation should encodeURI in ensureSlash

### PR DESCRIPTION
**Pull request by AsaAyers**
It decodes the path before operating on it, it should `encodeURI` before replacing it.

Without this change any URL that includes a properly encodes space (`%20`) gets converted to a space if the URL doesn't have a leading slash.

### CODE REVIEW

**Comment by ryanflorence** [comment]
thanks @AsaAyers can you add a test to make sure we don't screw this up again?

**Comment by AsaAyers** [comment]
I added the test and it passes locally, but TravisCI keeps disconnecting.

> INFO [Firefox 31.0.0 (Linux)]: Connected on socket _gjkzblmGZdn7RTYha7L with id 29196954
> WARN [Firefox 31.0.0 (Linux)]: Disconnected (1 times), because no message in 10000 ms.
> Firefox 31.0.0 (Linux): Executed 0 of 0 DISCONNECTED (11.078 secs / 0 secs)
> npm ERR! Test failed.  See above for more details.
> npm ERR! not ok code 0

**Comment by AsaAyers** [comment]
Can this get merged soon and released as `v0.12.5`? Because you're hiding `ensureSlash` using the module pattern, there's no way for me to just patch this at runtime, so I had to copy the entire file into my own project. But now I run into a new bug because you're explicitly looking for [*your* `HashLocation`](https://github.com/rackt/react-router/blob/10359a50cc6df934a10dea581a8ac81eeff68efd/modules/createRouter.js#L235) when generating links.

**Comment by AsaAyers** [comment]
I can't even patch `router.makeHref` with a compatible version because the [`NavigationContext`](https://github.com/rackt/react-router/blob/v0.12.4/modules/NavigationContext.js#L19) grabs a reference and binds the original function before I can ever get access to it.

**Comment by AsaAyers** [comment]
@ryanflorence I added the test over a month ago, and then asked again bout getting it merged 29 days ago. At this point I don't care if you release it as `v0.12.5` or not.

It doesn't look like we have any merge conflicts, so I assume this bug is still present in the current version.

**Comment by AsaAyers** [comment]
ping @ryanflorence 

The last build failure was because something in TravisCI crashed. I force-pushed to make it build again. I think watching TravisCI for 15 minutes is long enough. I assume it will pass.

**Comment by ryanflorence** [comment]
Sorry for the silence, as you might know @mjackson and I started a company and then focused our free time on the 1.0 API, we will get to this bug in the new code.

**Comment by mjackson** [comment]
I think this will probably be fixed by #1265.

**Comment by mjackson** [comment]
As of 41bd525c9209661a7ef4ea37037d35e727d595d1 [`getHashPath` no longer decodes the URL when reading it](https://github.com/rackt/react-router/blob/41bd525c9209661a7ef4ea37037d35e727d595d1/modules/DOMUtils.js#L5-L9), so we don't need to encode it in `ensureSlash`.

**Pull request closed without merging**
