### PR TITLE
Update our tested browsers

### PR DESCRIPTION
**Pull request by timdorr**
Firefox and Chrome were really old and auto-update now.

Also, iOS 9 and 8 distribution is high, so they should be tested too. Also bumped up Safari and used Windows 10 where possible.

### CODE REVIEW

**Comment by taion** [comment]
Chrome 39 is sorta special since it's what Travis uses. If we have something that's broken in Chrome 39, we're likely to cause pain to our users who use Travis for their CI.

**Comment by timdorr** [comment]
What if we ran against the installed version of Chrome, rather than via BrowserStack? That way we stay in lockstep if Travis ever updates their build environment again (no idea what the holdup is. It's been 8 months...)

**Comment by taion** [comment]
Sounds like a good idea to me. @mjackson, any thoughts?

Maybe we can configure this with `.travis.yml` `ENV`.

**Comment by timdorr** [comment]
I'll just make the BS config not overwrite the non-BS config. Should work fine.

**Comment by taion** [comment]
Might be worth updating rackt/history as well, then.

**Pull request merged**
