### PR TITLE
Expose needed functionality in UMD build

### PR DESCRIPTION
**Pull request by ghempton**

### CODE REVIEW

**Comment by timdorr** [comment]
What's the reasoning behind/need for this?

**Comment by ghempton** [comment]
Currently, in our routable components, we have access to things like `route`, `params`, `location`, etc. The one thing that is missing is the ability to figure out which part of the location a particular route matched– which can be determined via `formatPattern(this.props.route.path, this.props.params)`.

One use case is when creating a custom `<Link>` wrapper which supports relative links.

**Comment by ghempton** [comment]
If only our project used webpack instead of broccoli life would be so much easier

**Comment by taion** [comment]
Please drop the re-exports.

Per the docs, you should be getting those directly from `history`, then applying `useRouterHistory` to those.

Exposing `formatPattern` looks fine to me, though.

**Comment by ghempton** [comment]
@taion the UMD build embeds history now. There is no way to access it.

**Comment by taion** [comment]
But you can separately pull in `history` yourself, no?

**Comment by ghempton** [comment]
yes, but that would require two copies of history, since there is already one inside the react router UMD

**Comment by taion** [comment]
Let's consolidate discussion on #2808.

**Comment by taion** [comment]
I'd be okay to merge this with the re-exports dropped.

**Comment by ghempton** [comment]
done

**Comment by taion** [comment]
Thanks!

**Pull request merged**
