### PR TITLE
Add a memory history

### PR DESCRIPTION
**Pull request by timdorr**
As mentioned in 56d44968.

### CODE REVIEW

**Comment by timdorr** [comment]
Woah, wait. We have a `createMemoryHistory` now? Why does that not follow the singleton pattern of the other histories?

**Comment by taion** [comment]
Memory history isn't really singleton-ish. The `window.location` is a singleton that the others deal with, but you use memory history largely for things like tests or SSR, where having it be a singleton would be counterproductive.

**Comment by timdorr** [comment]
Hmm, that is true. I'll close this out then.

**Comment by ryanflorence** [comment]
Yep, exactly what @taion said, but I was tempted to have a singleton when writing that stuff.

**Pull request closed without merging**
