### PR TITLE
Added qs, deep-equal as dependencies

### LINKED ISSUE #2208: Upgrade to react-router rc2 problems
Hey all, I upgraded npm today in my project and it is now using react 0.14.. been using rc1 prior. Also was using react-router rc1. This update pushed me to react-router rc2. Now, when I start my npm, I get an issue with react-router cant find module qs as well as module deep-equal.

I tried to be clever.. so I went in to the node_modules/react-router and tried running npm install. When I do that I get the following error:

SyntaxError: modules/IndexRedirect.js: Unexpected token (25:19)
  23 |   }
  24 | 
> 25 |   static propTypes = {
     |                    ^
  26 |     to: string.isRequired,
  27 |     query: object,
  28 |     state: object,

Not sure if what I did was incorrect or not..was hoping by manually npm installing the two modules would magically appear and not clear why they are not there in the first place. I see them in package.json.

### PR DESCRIPTION
**Pull request by woodb**
So, I'm really not sure if this is the right way to solve whatever issue is
happening here, but adding these two dependencies does solve the immediate
issue that has been reported as #2208.

I wish that I had more time to investigate, but this does solve the issue
that's holding things up for me on another project.

Feel free to reject this PR if it's overkill, but maybe this'll help your
immediate problem @justjacksonn! Cheers.

Closes #2208

### CODE REVIEW

**Comment by knowbody** [comment]
that's what I did in #2204 but that's not the right solution anyway

**Comment by woodb** [comment]
> that's not the right solution anyway

I had a feeling hah, seemed like hitting a fly w/ a sledgehammer w/ the `deep-copy` dep... Thanks!

**Comment by woodb** [comment]
For anyone who stumbles upon this thread, please see #2195

**Comment by knowbody** [comment]
Yeah pretty much :smile:

**Pull request closed without merging**
