### PR TITLE
Removed parentheses after `new Hashhistory`

### PR DESCRIPTION
**Pull request by johanneslumpe**
Just so the examples are more consistent in that regard.

### CODE REVIEW

**Comment by mjackson** [comment]
Instead of adding unnecessary parens, lets remove them in the examples that have them.

**Comment by johanneslumpe** [comment]
Ok, done!

**Comment by johanneslumpe** [comment]
Something is wrong now...

**Comment by mjackson** [comment]
Thanks @johanneslumpe !

**Pull request merged**
