### PR TITLE
Update Introduction.md

### PR DESCRIPTION
**Pull request by maxdignan**
Fixed grammatical typo.

### CODE REVIEW

**Comment by taion** [comment]
That is a bit awkwardly phrased. I don't know that making it more clearly a parenthetical expression helps, though.

How about:
>If you're on `/foo?bar=baz`, you can access [...]

**Comment by maxdignan** [comment]
That seems fine to me. Sending another pR

**Comment by timdorr** [comment]
@maxdignan Can you just amend your commit on this one?

**Comment by maxdignan** [comment]
I'm lost on how to do this... I'll close this and reopen another pr.

**Pull request closed without merging**
