### PR TITLE
Fix v2 example for Navigating in Route Components

### PR DESCRIPTION
**Pull request by marksamman**

### CODE REVIEW

**Comment by taion** [comment]
Should we just be consistent with using `React.createClass` here?

**Comment by ryanflorence** [comment]
Yes

**Comment by marksamman** [comment]
I've updated the pull request using React.createClass. I've also updated two other examples where the React.PropTypes was missing infront of object.isRequired.

**Comment by timdorr** [comment]
Sweet! Thank you for doing that!

**Pull request merged**
