### PR TITLE
Prefer React.createClass over react-mixin

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by omnidan** [comment]
@taion I'm a bit confused - why is this a better way to do it? I always thought it was just a preference thing

**Comment by taion** [comment]
It's a little bit inelegant with `react-mixin` still because you have to manually bind the `routerWillLeave` hook. It's definitely up to user preference in the end, but on further thought and from talking to @ryanflorence, I think given a choice, I'd lean very slightly toward recommending using `React.createClass` over `react-mixin` to users who need advice on this in the first place.

I'm personally going to use `react-mixin`, but I think users checking these docs would be better served by dropping to `React.createClass`.

**Comment by omnidan** [comment]
Ah, that totally makes sense then - it's also good to avoid using brand-new syntax (decorators are ES7) for general understanding.

**Comment by taion** [comment]
Yup - I think we still want to point users at `react-mixin`, just... with a bit less enthusiasm.

**Comment by omnidan** [comment]
@taion yeah, maybe just note it: "Note: If you're using ES7 decorators, you can try out `react-mixin`" or something like that

**Comment by taion** [comment]
Well, the react-mixin thing works regardless. If users are comfortable/familiar with it, they'll know what to do. If not, then they probably should use `createClass`.

**Pull request merged**
