### PR TITLE
Scroll element referenced by hash into view on Link click

### PR DESCRIPTION
**Pull request by aszwemin**

### CODE REVIEW

**Comment by knowbody** [comment]
@aszwemin should this be referenced to some issue? because the tests are failing on this PR

**Comment by aszwemin** [comment]
@knowbody It's related to discussion in https://github.com/rackt/react-router/pull/2224 - gonna have a look what's failing in the tests

**Comment by knowbody** [comment]
cool! thanks :)

**Comment by taion** [comment]
Wait how is this supposed to work? `pushState` doesn't always do a synchronous route transition.

**Comment by aszwemin** [comment]
@taion good point. promise or is there an easier solution here?

**Comment by aszwemin** [comment]
Closing for now, will come back to it next week, as won't have a chance until then

**Pull request closed without merging**
