### PR TITLE
Remove default Router export

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by timdorr** [comment]
I'm similarly meh on this. It will break (trivially) some existing uses, but would be good to make it clear that you need more than just the default import.

**Comment by taion** [comment]
You can't do anything useful if you're just using the default export anyway, since you'd (almost) always need `<Route>` anyway.

**Comment by timdorr** [comment]
Yeah, that's why I'm only meh on this. The breakage isn't that big of a deal.

**Comment by ryanflorence** [comment]
Just realized the best argument for this is when people do this:

`import Link from 'react-router'`

They render a bunch of routers all over the place and have no clue what is happening!

**Comment by ryanflorence** [comment]
Also, can we get an entry in the CHANGES.md about this? Somebody somewhere is using it.

**Pull request merged**
