### PR TITLE
[README.md] Add --save to install command

### PR DESCRIPTION
**Pull request by andreynering**

### CODE REVIEW

**Comment by timdorr** [comment]
That's not needed to install the module. It assume you want to use it permanently when you might just be trying it out.

**Comment by taion** [comment]
@timdorr It looks more common than not for other packages to do this, though – check the install instructions for React and Redux, for example.

**Comment by taion** [comment]
It is a little extraneous but it might be a nice affordance to users who are less familiar with npm.

**Comment by timdorr** [comment]
It doesn't matter to me.

**Pull request merged**
