### PR TITLE
Add testlocation to exported API

### PR DESCRIPTION
**Pull request by tarjei**
To make testing easier.

refs #678

### CODE REVIEW

**Comment by mjackson** [comment]
Exporting `TestLocation` means it will be included in browser builds. That's the main reason I didn't include it in the first place.

**Comment by tarjei** [comment]
Hmm,that is a major point :/

Hmm, Maybe you could add a TestHelpers.js file at the bottom? I.e.
```js
require('react-routers/TestHelpers').TestLocation

```

I'm planning to try to do a writeup testing when I'm done refactoring my > 1000 tests.

**Comment by mjackson** [comment]
@tarjei Ya, I like that idea. Let's call it `TestUtils` for consistency with `ReactTestUtils`.

**Comment by mjackson** [comment]
@tarjei As of 81c7a5785272970f246fefcec1642b9ca372155e you can just

```js
var TestLocation = require('react-router/locations/TestLocation');
```

Is that easy enough?

**Comment by tarjei** [comment]
Nice!
17. jan. 2015 19:37 skrev "Michael Jackson" <notifications@github.com>:

**Comment by rpflorence** [comment]
seems like everybody is happy, closing. let me know if I should reopen.

**Pull request closed without merging**
