### PR TITLE
Add support for redirects in plain routes

### PR DESCRIPTION
**Pull request by hellosmithy**
Fixes https://github.com/rackt/react-router/issues/1632

e.g.

```
let routes = [
	{ from: '/', to: '/begin' },
	{
		path: '/',
		component: App,
		childRoutes: [
			{ path: '/begin', component: Begin },
			
			{ from: '/about', to: '/about-us' },
			{ path: '/about-us', component: AboutUs }
		]
	}
];
```

### CODE REVIEW

**Comment by hellosmithy** [comment]
This functionality is repeated here and in `Redirect.js` so there migh be a case for abstracting it out into a util

**Comment by hellosmithy** [comment]
ping @ryanflorence @mjackson

**Comment by mjackson** [comment]
I'm not 100% sure we want "plain routes" to be public API at this point. It all just feels like machine-generated code.

**Comment by hellosmithy** [comment]
I agree it doesnt really feel like public facing API. But still quite limiting to not be able to do redirects.

**Comment by hellosmithy** [comment]
How would you feel about them being more like a normal route object with path? e.g.

```
{
    path: '/',
    redirectTo: '/begin'
}
```

**Comment by ryanflorence** [comment]
we don't need to touch the existing code, just need something like this:

```js
I've done this, maybe should add it to the api? I dunno. Closing in favor of 

```js
function redirect (from, to) {
  return {
    path: from,
    onEnter (nextState, transition) => {
      transition.to(to)
    }
  }
}
```

and then

```js
var routes = {
  path: '/'
  component: App,
  childRoutes: [
    redirect('/users', '/people'),
    // ...
  ]
}
```

**Comment by hellosmithy** [comment]
@ryanflorence ok this seems like a better solution

**Comment by web2style** [comment]
`transition` no longer has 'to' method so it should be just:
```
function redirect(from, to) {
  return {
    path: from,
    onEnter: (nextState, transition) => {
      transition(to);
    }
  }
}
```

**Comment by jahed** [comment]
The given alternatives don't work with parametrised routes whereas `<Redirect />` does. Is there a way to do this without repeating/copypasting Redirect's functionality?

**Pull request closed without merging**
