### PR TITLE
[fixed] Support qs 3.x #1249

### PR DESCRIPTION
**Pull request by mikepb**
Use `hasOwnProperty` from `{}` instead of from `qs` object.

### CODE REVIEW

**Comment by felipeleusin** [comment]
Got stuck on this, had to go back to qs 2.4.2. Just checking wouldn't be better to use Object.prototype.hasOwnProperty?

**Comment by mikepb** [comment]
`Object.prototype.hasOwnProperty` works too, I like `({}).hasOwnProperty` because it's more terse. I'm not sure if there are some old browsers out there that have one or the other.

**Comment by felipeleusin** [comment]
Yeah, I was just curious about the two... Still, thanks for the PR! Will wait for it to be merged

**Comment by ryanflorence** [comment]
Is this still a problem on latest master? Sorry for the long-lived `next` branch.

(Also, note on master that query parsing is now pluggable, so if we encounter a problem with qs in the future, you can just plug in your own)

**Comment by mjackson** [comment]
This PR is out of date.

In any case, we should always use `Object.prototype.hasOwnProperty`. If someone else is mucking with that, it's their problem, not ours.

**Pull request closed without merging**
