### PR TITLE
Update React.render to ReactDOM.render for 1.0

### PR DESCRIPTION
**Pull request by goldensunliu**

### CODE REVIEW

**Comment by knowbody** [comment]
make it just:

```js
render
```

as you would:
```js
import { render } from 'react-router' 
```

**Comment by goldensunliu** [comment]
where should we include the:
``` javascript
import { render } from 'react-dom' 
```
in this doc, just to be more explicit

**Comment by knowbody** [comment]
just on top of the code example to be clear, I think it's just two of them

**Comment by goldensunliu** [comment]
@knowbody done1

**Comment by knowbody** [comment]
thanks, @goldensunliu can you squash your commits?

**Comment by goldensunliu** [comment]
@knowbody good to go

**Comment by taion** [comment]
Stealing the big green button.

**Comment by knowbody** [comment]
haha

**Pull request merged**
