### PR TITLE
Fixes false positives in Link isActive checks

### PR DESCRIPTION
**Pull request by bmathews**
This is intended to fix https://github.com/rackt/react-router/issues/1441.

It's possible that you have better ideas in mind for solving this, so feel free to disregard this PR if that's the case. 

I pulled the path matching code into URLUtils so that they're easier to test. Maybe it's possible to re-use some of the existing pattern matching, but I didn't see an easy way.

### CODE REVIEW

**Comment by gonsfx** [comment]
Doesn't seem to work. Needs to take route hierarchy into account.

**Comment by bmathews** [comment]
@gonsfx Can you elaborate? Do you have a test case that it doesn't pass?

**Comment by bmathews** [comment]
@gonsfx Oh I see what you mean. Rather than match based on the URL, match on the route component hierarchy.

**Comment by gonsfx** [comment]
A typical example i cross-posted into other issues would be

```jsx
<Router history={new BrowserHistory}>
  <Route component={App}>
    <Route path="/" component={HomePage}>
      <Route path="nested" component={NestedPage}>
        <Route path="nested" component={NestedPage} />
      </Route>
      <Route path="nest" component={NestPage} />
    </Route>
    <Route path="some" component={SomePage} />
    <Route path="other" component={OtherPage} />
  </Route>
</Router>
```

**Pull request closed without merging**
